const app = require('../server')
const MIDDLEWARE = require('./middleware/index')
const CONTROLLER = require('./actionController/index')
const ROUTES = require('./routes')

app.get(ROUTES.ROOT, async (req, res) => {
    res.json(ROUTES)
})
app.get(ROUTES.USER_LEVEL, CONTROLLER.GET_USER_LEVEL)
app.get(ROUTES.USER_INFORMATION, CONTROLLER.GET_USER_INFORMATION)
app.get(ROUTES.RIOT_API_KEY, CONTROLLER.GET_RIOT_API_KEY)

app.post(
    ROUTES.RIOT_API_KEY,
    MIDDLEWARE.CHECK_RIOT_KEY,
    MIDDLEWARE.CREATE_DB_RIOT_KEY,
    CONTROLLER.SET_RIOT_KEY
)

app.post(
    ROUTES.SIGNUP,
    MIDDLEWARE.CHECK_USERNAME_AVAILABILITY,
    MIDDLEWARE.CHECK_EMAIL_AVAILABILITY,
    CONTROLLER.SIGNUP
)

app.post(ROUTES.LOGIN, MIDDLEWARE.CHECK_IF_USERNAME_EXISTS, CONTROLLER.LOGIN)
